### ISSUE TITLE
Add support for last serial in execute

### ISSUE THREAD

**Issue by Thiltal** [xxgreg/dart_postgresql#56]
Upgrade conn.exectue to return also last serial, not even number of affected rows.
http://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id

**Comment by tomyeh** [comment]
IMO, it is not the job of execute() to return the serial number. Rather, the application shall issue another query to get it back:

    connectquery("select currval('\"${YourTable}_${YourPK}_seq\"')")

**Comment by xxgreg** [comment]
The most common way to do this in postgresql is to use a returning clause. One advantage of using this is it also supports inserting/updating multiple rows.

For example:

    c.query('insert into my_table (id, value) values (default, 'blah') returning id;').single.then((row) {
      print(row.id);
    });

**Comment by Thiltal** [comment]
Ok, last inserted serial is not part of Connection.execute. I will close this issue.
