### ISSUE TITLE
Provide the table object id for selected rows/columns

### ISSUE THREAD

**Issue by Pajn** [xxgreg/dart_postgresql#63]
You store the object id as `fieldId` in `_Column`, however you provide no way to publicly access this value.

I would need to access to it, to keep track of which columns comes from which tables in a JOIN.
See the [sqljocky](https://pub.dartlang.org/packages/sqljocky) package for an example of providing this information.

**Comment by xxgreg** [comment]
Could you give me an example of what you're trying to achieve. I'd typically do this by providing a detailed column name in an alias (as clause), but perhaps I don't understand the problem you're trying to solve.

Exposing the column information seems like a good idea. I'd recommend adding a method to the Row class like `List<Column> toColumns()`, which exposes a public Column class. Patches welcome :+1:  If it has tests, I will be able to merge it pretty quickly.

**Comment by Pajn** [comment]
Basically an ORM. I could select and alias every column but with the id I doesn't have to. I have an already working implementation against mySQL where the information already is provided.

I guess the change should be quite simple so I can work on a PR when I get time.

**Comment by Pajn** [comment]
#64 Solves my use case, I'm currently using that branch
