### ISSUE TITLE
connect() fails when database name contains spaces

### ISSUE THREAD

**Issue by chadschw** [xxgreg/dart_postgresql#67]
Unfortunately I cannot change the name of the database. 

Here is an example of uri string I am using:

String uri = "postgres://my_username:my_password@127.0.0.1:5434/my database";

Passing that URI string to connect() produces this exception:

Unhandled exception:
Uncaught Error: FATAL 3D000 database "my%20database" does not exist
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

I have tried wrapping the database name in single quotes and get the same error with the single quotes urlencoded as well.

**Comment by Fox32** [comment]
Maybe you have to modify [this line](https://github.com/xxgreg/dart_postgresql/blob/master/lib/src/postgresql_impl/connection.dart#L14 ) to decode the database name using [Uri.decodeFull](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.Uri#id_decodeFull)

**Comment by chadschw** [comment]
Thank you for the pointer. I've confirmed your suggestion works and I think I've made a pull request for the change (my first time so I'm not confident I did things correctly).

**Comment by Fox32** [comment]
I think @xxgreg is happy if you send a contribution =)

**Comment by xxgreg** [comment]
Good suggestion Oliver. The settings class is definitely the correct place to make a change.

**Comment by xxgreg** [comment]
Thanks for this Chad. I've merged your change and published version 0.3.2 on pub.

Please give it a shot and let me know if there are any problems.
