### ISSUE TITLE
Feature: executeMulti 

### ISSUE THREAD

**Issue by lteacher** [xxgreg/dart_postgresql#75]
Hello,

There was some reference in an unrelated issue #24 to an idea of having the `executeMulti` or similar. Was there any further thought or development on that idea? Maybe i missed it somewhere or its not documented, however, it seems useful. The `sqljocky` does have this and it would be beneficial for me to have it so I wanted to ask here.

For clarity the suggestion is, some method like `executeMulti` that can do `List<List>` or `List<Map>` e.g. 

``` dart
executeMulti('insert into my_table values (@a, @b, @c)', [
  {"a": 1, "b": 2, "c": 3},
  {"a": 4, "b": 5, "c": 6},
  {"a": 7, "b": 8, "c": 9},
]))

// And (if i have this syntax correct...)
executeMulti('insert into my_table values (@0, @1, @2)', [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
]))
```

**Comment by lteacher** [comment]
Obviously I implemented in fork per above awaiting any replies for this one.

**Comment by xxgreg** [comment]
Apologies - I am totally snowed under at the moment. I'd recommend implementing executeMulti in a separate package for now. 

Given the simple query protocol that this driver uses there isn't a performance benefit to baking this into the existing library. So the main concern is the user API, which in most cases I imagine will be some kind of ORM.

For this library I am willing to help with bug fixes, but not really planning on adding new features for the time being.

**Comment by lteacher** [comment]
Hi @xxgreg 

I understand. You are correct I am working on an ORM implementation and indeed there is no performance improvement that I can imagine, its only the api. In saying that per your comments I did implement the feature I believe to an acceptable standard.

I am depending on the fork at the moment. Maybe I can just create the pull request, you could then reject or review when you have time its up to you. Of course I would prefer to depend on this package directly rather than having some split.
