### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by artem-malko** [xxgreg/dart_postgresql#79]
https://drone.io/github.com/xxgreg/postgresql/latest

It seems, that where is an error in code.

**Comment by xxgreg** [comment]
I think drone isn't updating the dart sdk version anymore.

Should probably switch over to travis. Happy to take pull requests either just removing drone support, or switching to travis.

Have a look at mustache for an example.
https://github.com/xxgreg/mustache

(Hmm that's marked as failing too - doh!)

**Comment by xxgreg** [comment]
Ok - some procrastination. Fixed.
