### ISSUE TITLE
No constructor 'MD5' declared in class 'MD5'

### ISSUE THREAD

**Issue by mkhan-akhan** [xxgreg/dart_postgresql#81]
Dependencies as follows:
================

name: seven_arabic
version: 0.9.5
Environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  angular: '>=1.1.0 <2.0.0'
  angular_ui: '>=0.6.6 <0.7.0'
  browser: '>=0.10.0+2 <0.11.0'
  shadow_dom: any
  web_components: any
  js: any
  http: any
  logging: any
  logging_handlers: any
  rpc: any
  shelf: any
  shelf_route: any
  shelf_rpc: any
  toml: any
  postgresql: any
transformers:
- angular
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]

Error as follows:
==========

"C:\Program Files\Dart\dart-sdk\bin\dart.exe" --ignore-unrecognized-flags --checked --pause_isolates_on_start --enable-vm-service:49806 --trace_service_pause_events D:\Users\Mohammed\Documents\dart\seven_arabic\bin\web_server.dart
Observatory listening on http://127.0.0.1:49806
Listening at port 8090.
ERROR - 2016-09-26 10:15:11.622631
Asynchronous error
No constructor 'MD5' declared in class 'MD5'.

NoSuchMethodError: method not found: 'MD5'
Receiver: Type: class 'MD5', args:[TypeArguments: (400656641) [Type: class 'List', args:[TypeArguments: (198535643) [Type: class 'int']]] [Type: class 'Digest'] [Type: class 'List', args:[TypeArguments: (198535643) [Type: class 'int']]] [Type: class 'Digest']]
Arguments: [...]
dart:core                                 NoSuchMethodError._throwNew
package:postgresql/connection.dart 56:23  _Connection._md5s
package:postgresql/connection.dart 7:23   _Connection._Connection
package:postgresql/connection.dart 46:24  _Connection._connect.<fn>.<fn>

Package Versions
============
postgresql 0.2.10
crypto 1.1.1

**Comment by mkhan-akhan** [comment]
Added dependency:
 crypto: ">=0.9.0 <0.10.0"

Which solved the issue.

postgresql package was automatically resolved to  0.3.3

**Comment by xxgreg** [comment]
Sorry about that. I think Oliver has a pull request for this. I've been way
too busy to merge it. https://github.com/xxgreg/dart_postgresql/pull/80

**Comment by xxgreg** [comment]
I've merged Olivers PR. Try using version 0.3.4 from pub and let me know if this fixes your problem.

**Comment by mkhan-akhan** [comment]
Yes, it definitely has :). Many thanks.

**Comment by xxgreg** [comment]
;)
